### ISSUE TITLE
(WIP) Promise-generator-based build/task system

### ISSUE THREAD

**Issue by charlike** [charlike/blankr#6]
- no dependency functionality as in `gulp.task('task3', ['task1', 'task2'], handler)` or as in `gulp.start('default', ['task1', 'task3', 'task2'])`
- convert anything to promise
- on top of promiz.js?
- separate modules
- readdir stream lib
- globs lib
- generators mode for yielding
- no need to have plugins, all will work just with native modules in tasks

``` js
promiz().task('taskName', function * (onFullfilled, onRejected) {
  // some logic; streaming get files from globs
  return promis
}, console.error)
.all()
.task('task2', function * (list, onRejected) {
  //async foreach open/read each file and send content to next promise
  return promis
}, console.error)
.task('compiles', function * (fileContent, onRejected) {
  //list
  return promis
}, console.error)


// custom start some task promise
promiz().start('task2')
```

**Comment by tunnckoCore** [comment]
Pretty near to this one, because of latest @hybridables

**Comment by charlike** [comment]
pretty old :laughing:
